<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>07f46673-f560-4b48-b279-56a2853f4845</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Protobuf Include="Protos\blockchain.proto" GrpcServices="Both" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.57.0" />
    <PackageReference Include="Grpc.AspNetCore.Web" Version="2.76.0" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.7" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlcipher" Version="2.1.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Blockchain.Core\Blockchain.Core.csproj" />
  </ItemGroup>

</Project>
